language: node_js
node_js:
  - '6'
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls'
addons:
  apt:
    packages:
      - oracle-java8-set-default
services:
  - postgresql
script:
  - npm run test
